CREATE TABLE visual_content_library (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    community_id UUID REFERENCES communities(id),
    content_type VARCHAR(50) NOT NULL CHECK (content_type IN ('image',
    'video',
    'infographic',
    'meme',
    'chart')),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    file_url TEXT NOT NULL,
    thumbnail_url TEXT,
    tags JSONB DEFAULT '[]',
    engagement_metrics JSONB DEFAULT '{}',
    ai_generated BOOLEAN DEFAULT false,
    generation_prompt TEXT,
    curator_id UUID REFERENCES profiles(id),
    approval_status VARCHAR(50) DEFAULT 'pending' CHECK (approval_status IN ('pending',
    'approved',
    'rejected')),
    view_count INTEGER DEFAULT 0,
    like_count INTEGER DEFAULT 0,
    share_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);