CREATE TABLE federated_learning_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_name VARCHAR(255) NOT NULL,
    job_type VARCHAR(50) CHECK (job_type IN ('horizontal',
    'vertical',
    'cross_device',
    'cross_silo')),
    framework VARCHAR(50) CHECK (framework IN ('flower',
    'tensorflow_federated',
    'unified')),
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending',
    'running',
    'completed',
    'failed',
    'cancelled')),
    model_config JSONB NOT NULL,
    data_config JSONB NOT NULL,
    num_clients INTEGER NOT NULL CHECK (num_clients > 0),
    num_rounds INTEGER NOT NULL CHECK (num_rounds > 0),
    current_round INTEGER DEFAULT 0,
    privacy_budget DECIMAL(10,4) DEFAULT 8.0,
    performance_metrics JSONB DEFAULT '{}',
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);