# Azure Cluster Configuration using Cluster API

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: trustram-azure-cluster
  namespace: multi-cloud-system
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.129.0.0/12"]
    pods:
      cidrBlocks: ["192.169.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureCluster
    name: trustram-azure-cluster
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: trustram-azure-control-plane

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: trustram-azure-cluster
  namespace: multi-cloud-system
spec:
  location: "East US"
  resourceGroup: "trustram-rg"
  subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
  networkSpec:
    vnet:
      name: "trustram-vnet"
      cidrBlocks:
        - "10.0.0.0/8"
    subnets:
      - name: "control-plane-subnet"
        cidrBlocks:
          - "10.0.0.0/16"
        role: "control-plane"
      - name: "node-subnet"
        cidrBlocks:
          - "10.1.0.0/16"
        role: "node"

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: trustram-azure-control-plane
  namespace: multi-cloud-system
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
          feature-gates: "CSIMigration=true,CSIMigrationAzureDisk=true,CSIMigrationAzureFile=true"
      controllerManager:
        extraArgs:
          cloud-provider: external
          feature-gates: "CSIMigration=true,CSIMigrationAzureDisk=true,CSIMigrationAzureFile=true"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
  machineTemplate:
    infrastructureRef:
      kind: AzureMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: trustram-azure-control-plane
  replicas: 3
  version: v1.28.3

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: trustram-azure-control-plane
  namespace: multi-cloud-system
spec:
  template:
    spec:
      vmSize: "Standard_D2s_v3"
      image:
        marketplace:
          publisher: "Canonical"
          offer: "0001-com-ubuntu-server-focal"
          sku: "20_04-lts-gen2"
          version: "latest"
      osDisk:
        osType: "Linux"
        diskSizeGB: 128
        managedDisk:
          storageAccountType: "Premium_LRS"
      sshPublicKey: "${AZURE_SSH_PUBLIC_KEY_B64}"

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: trustram-azure-md-0
  namespace: multi-cloud-system
spec:
  clusterName: trustram-azure-cluster
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: trustram-azure-cluster
  template:
    spec:
      clusterName: trustram-azure-cluster
      version: v1.28.3
      bootstrap:
        configRef:
          name: trustram-azure-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: trustram-azure-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachineTemplate

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: trustram-azure-md-0
  namespace: multi-cloud-system
spec:
  template:
    spec:
      vmSize: "Standard_D4s_v3"
      image:
        marketplace:
          publisher: "Canonical"
          offer: "0001-com-ubuntu-server-focal"
          sku: "20_04-lts-gen2"
          version: "latest"
      osDisk:
        osType: "Linux"
        diskSizeGB: 128
        managedDisk:
          storageAccountType: "Premium_LRS"
      sshPublicKey: "${AZURE_SSH_PUBLIC_KEY_B64}"
      role: "Node"

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: trustram-azure-md-0
  namespace: multi-cloud-system
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external