# GCP Cluster Configuration using Cluster API

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: trustram-gcp-cluster
  namespace: multi-cloud-system
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.130.0.0/12"]
    pods:
      cidrBlocks: ["192.170.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPCluster
    name: trustram-gcp-cluster
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: trustram-gcp-control-plane

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: trustram-gcp-cluster
  namespace: multi-cloud-system
spec:
  project: "${GCP_PROJECT}"
  region: "us-central1"
  network:
    name: "trustram-network"
    subnets:
    - name: "control-plane-subnet"
      cidrBlock: "10.0.0.0/16"
      region: "us-central1"
    - name: "node-subnet"
      cidrBlock: "10.1.0.0/16"
      region: "us-central1"
      secondaryIpRanges:
        pods: "192.170.0.0/16"
        services: "10.130.0.0/12"

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: trustram-gcp-control-plane
  namespace: multi-cloud-system
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
          feature-gates: "CSIMigration=true,CSIMigrationGCE=true"
      controllerManager:
        extraArgs:
          cloud-provider: external
          feature-gates: "CSIMigration=true,CSIMigrationGCE=true"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
  machineTemplate:
    infrastructureRef:
      kind: GCPMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: trustram-gcp-control-plane
  replicas: 3
  version: v1.28.3

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: trustram-gcp-control-plane
  namespace: multi-cloud-system
spec:
  template:
    spec:
      machineType: "e2-standard-2"
      image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts"
      disks:
      - size: 128
        type: "pd-ssd"
        boot: true
        autoDelete: true
      subnet: "control-plane-subnet"
      publicIP: false
      serviceAccounts:
        email: "${GCP_CONTROL_PLANE_SA}"
        scopes:
        - "https://www.googleapis.com/auth/compute"
        - "https://www.googleapis.com/auth/devstorage.read_only"
        - "https://www.googleapis.com/auth/logging.write"
        - "https://www.googleapis.com/auth/monitoring"

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: trustram-gcp-md-0
  namespace: multi-cloud-system
spec:
  clusterName: trustram-gcp-cluster
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: trustram-gcp-cluster
  template:
    spec:
      clusterName: trustram-gcp-cluster
      version: v1.28.3
      bootstrap:
        configRef:
          name: trustram-gcp-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: trustram-gcp-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPMachineTemplate

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: trustram-gcp-md-0
  namespace: multi-cloud-system
spec:
  template:
    spec:
      machineType: "e2-standard-4"
      image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts"
      disks:
      - size: 128
        type: "pd-ssd"
        boot: true
        autoDelete: true
      subnet: "node-subnet"
      publicIP: false
      serviceAccounts:
        email: "${GCP_NODE_SA}"
        scopes:
        - "https://www.googleapis.com/auth/compute"
        - "https://www.googleapis.com/auth/devstorage.read_only"
        - "https://www.googleapis.com/auth/logging.write"
        - "https://www.googleapis.com/auth/monitoring"

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: trustram-gcp-md-0
  namespace: multi-cloud-system
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external