# AWS Cluster Istio Remote Configuration

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: remote-aws
  namespace: istio-system
spec:
  values:
    global:
      meshID: trustram-mesh
      multiCluster:
        clusterName: aws-cluster
      network: aws-network
      remotePilotAddress: "${MANAGEMENT_CLUSTER_ISTIOD_IP}"
    pilot:
      env:
        EXTERNAL_ISTIOD: true
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
    istiodRemote:
      enabled: true
  components:
    pilot:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: LoadBalancer
    - name: istio-eastwestgateway
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
      enabled: true
      k8s:
        service:
          type: LoadBalancer
          ports:
          - port: 15021
            targetPort: 15021
            name: status-port
          - port: 15443
            targetPort: 15443
            name: tls

---
# Expose Istiod for remote clusters
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istiod-gateway
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
  - port:
      number: 15010
      name: tls-istiod
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"
  - port:
      number: 15011
      name: tls-istiodwebhook
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"
  - port:
      number: 15012
      name: tls-istiodcert
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*"

---
# Virtual Service for Istiod
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istiod-vs
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - istiod-gateway
  tls:
  - match:
    - port: 15010
      sniHosts:
      - "*"
    route:
    - destination:
        host: istiod.istio-system.svc.cluster.local
        port:
          number: 15010
  - match:
    - port: 15011
      sniHosts:
      - "*"
    route:
    - destination:
        host: istiod.istio-system.svc.cluster.local
        port:
          number: 15011
  - match:
    - port: 15012
      sniHosts:
      - "*"
    route:
    - destination:
        host: istiod.istio-system.svc.cluster.local
        port:
          number: 15012

---
# Cross-network gateway for AWS
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cross-network-gateway-aws
  namespace: istio-system
spec:
  selector:
    istio: eastwestgateway
  servers:
  - port:
      number: 15443
      name: tls
      protocol: TLS
    tls:
      mode: ISTIO_MUTUAL
    hosts:
    - cross-network.local

---
# Destination Rule for AWS cross-cluster communication
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cross-cluster-aws
  namespace: istio-system
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  exportTo:
  - "*"